version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - baas

  kibana:
    container_name: kibana
    image: kibana:latest
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - SERVER_BASEPATH=/kibana
    networks:
      - baas

  nginx:
    container_name: nginx
    image: ${NGINX_IMAGE}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${NGINX_DEFAULT_CONFIG_FILE}:/etc/nginx/conf.d/default.conf
      - ${NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf 
    depends_on:
      - kibana
      - elasticsearch
    networks:
      - baas

  filebeat:
    container_name: filebeat
    image: filebeat:latest
    volumes:
      - ${FILEBEAT_CONFIG_FILE}:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
    networks:
      - baas

networks:
  baas:
    name: baas